ProvaFacil/ProvaFacil/Models/Prova.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace ProvaFacil.Models
{
    public class Prova
    {
        public int Id { get; set; }
        public Assunto Assunto { get; set; }
        public Cabecalho Cabecalho { get; set; }
        public Colegio Colegio { get; set; }
        public Materia Materia { get; set; }
        public Opcao Opcao { get; set; }
        public Questao Questao { get; set; }
        public Turma Turma { get; set; }

        // Lista de questões
        public List<Questao> ListaQuestoes { get; set; }

        public HttpPostedFileBase ImagemEscolhida { get; set; }
    }
}

ProvaFacil/ProvaFacil/Controllers/ProvaController.cs
using ProvaFacil.Context;
using ProvaFacil.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Web;
using System.Web.Mvc;
using System.Data.Entity;
using System.Net;
using Rotativa;

namespace ProvaFacil.Controllers
{
    public class ProvaController : Controller
    {
        private Contexto db = new Contexto();

        #region Métodos
        private void VerifTipoQuestao(Prova prova)
        {
            if (prova.Questao.Tipo_questao == "Múltipla escolha")
            {
                // Seta o número de linhas, já que não é uma questão dissertativa.
                prova.Questao.Numero_linhas = null;

                // Cria uma lista de opções de múltipla escolha para salvar no banco as opções digitadas.
                List<Opcao> opcoes = new List<Opcao>()
                        {
                            new Opcao() { Descricao_opcao = prova.Opcao.Descricao_opcaoMult1 },
                            new Opcao() { Descricao_opcao = prova.Opcao.Descricao_opcaoMult2 },
                            new Opcao() { Descricao_opcao = prova.Opcao.Descricao_opcaoMult3 },
                            new Opcao() { Descricao_opcao = prova.Opcao.Descricao_opcaoMult4 },
                            new Opcao() { Descricao_opcao = prova.Opcao.Descricao_opcaoMult5 },
                        };

                // Verifica qual é opção correta marcada pelo usuário para salvar e enviar ao banco.
                switch (prova.Opcao.Opcao_correta_escolhidaMult)
                {
                    case "1":
                        opcoes[0].Opcao_correta = true;
                        break;
                    case "2":
                        opcoes[1].Opcao_correta = true;
                        break;
                    case "3":
                        opcoes[2].Opcao_correta = true;
                        break;
                    case "4":
                        opcoes[3].Opcao_correta = true;
                        break;
                    case "5":
                        opcoes[4].Opcao_correta = true;
                        break;
                    default:
                        break;
                }
                db.Opcao.AddRange(opcoes);
            }

            else if (prova.Questao.Tipo_questao == "Verdadeiro/falso")
            {
                // Seta o número de linhas, já que não é uma questão dissertativa.
                prova.Questao.Numero_linhas = null;

                // Cria uma lista de opções de verdadeiro/falso para salvar no banco as opções digitadas.
                List<Opcao> opcoes = new List<Opcao>()
                        {
                            new Opcao() { Descricao_opcao = prova.Opcao.Descricao_opcaoVF1 },
                            new Opcao() { Descricao_opcao = prova.Opcao.Descricao_opcaoVF2 },
                            new Opcao() { Descricao_opcao = prova.Opcao.Descricao_opcaoVF3 },
                            new Opcao() { Descricao_opcao = prova.Opcao.Descricao_opcaoVF4 },
                            new Opcao() { Descricao_opcao = prova.Opcao.Descricao_opcaoVF5 },
                        };

                // Verifica quais opções estão marcadas entre Verdadeiro e Falso e salva para enviar ao banco.
                switch (prova.Opcao.Opcao_correta_escolhidaVF1)
                {
                    case true:
                        opcoes[0].Opcao_correta = true;
                        break;
                    case false:
                        opcoes[0].Opcao_correta = false;
                        break;
                    default:
                        break;
                }
                switch (prova.Opcao.Opcao_correta_escolhidaVF2)
                {
                    case true:
                        opcoes[1].Opcao_correta = true;
                        break;
                    case false:
                        opcoes[1].Opcao_correta = false;
                        break;
                    default:
                        break;
                }
                switch (prova.Opcao.Opcao_correta_escolhidaVF3)
                {
                    case true:
                        opcoes[2].Opcao_correta = true;
                        break;
                    case false:
                        opcoes[2].Opcao_correta = false;
                        break;
                    default:
                        break;
                }
                switch (prova.Opcao.Opcao_correta_escolhidaVF4)
                {
                    case true:
                        opcoes[3].Opcao_correta = true;
                        break;
                    case false:
                        opcoes[3].Opcao_correta = false;
                        break;
                    default:
                        break;
                }
                switch (prova.Opcao.Opcao_correta_escolhidaVF5)
                {
                    case true:
                        opcoes[4].Opcao_correta = true;
                        break;
                    case false:
                        opcoes[4].Opcao_correta = false;
                        break;
                    default:
                        break;
                }
                db.Opcao.AddRange(opcoes);
            }
        }

        private bool VerifSomaQuestoes(Prova prova, bool correto = true)
        {
            prova.ListaQuestoes = db.Questao.Where(q => q.Cod_prova == prova.Cabecalho.Cod_prova).ToList();
            decimal somaQuestoes = 0;
            if (prova.Questao.Valor_questao != null)
            {
                somaQuestoes = Convert.ToDecimal(prova.Questao.Valor_questao);
            }

            for (int i = 0; i < prova.ListaQuestoes.Count; i++)
            {
                if (prova.ListaQuestoes[i].Valor_questao != null)
                {
                    somaQuestoes += Convert.ToDecimal(prova.ListaQuestoes[i].Valor_questao);
                }
            }

            if (somaQuestoes > prova.Cabecalho.Valor_prova)
            {
                // Busca a lista de questões da prova inserida.
                prova.ListaQuestoes = db.Questao.Where(q => q.Cod_prova == prova.Cabecalho.Cod_prova).ToList();
                ViewBag.Sucesso = "ErroQuestoes";
                //ModelState.AddModelError("", "A soma do valor das questões não pode ser maior que o valor da prova.");
                correto = false;
            }
            return correto;
        }

        private int PegaUsuarioLogado()
        {
            var identity = (ClaimsIdentity)User.Identity;
            return int.Parse(identity.Claims.Where(c => c.Type == ClaimTypes.Sid).FirstOrDefault().Value);
        }

        private bool VerifId(int? id, bool existe = true)
        {
            // Se não for passado um ID para ver os detalhes, redireciona para a página da lista de provas.
            if (id == null)
            {
                existe = false;
                return existe;
            }

            // Se não for encontrado uma prova com o ID, redireciona para a página da lista de provas.
            var queryProva = db.Cabecalho.Find(id);
            if (queryProva == null)
            {
                existe = false;
                return existe;
            }

            // Se a prova encontrada não pertencer ao usuário logado, redireciona para a página da lista de provas.
            if (queryProva.Cod_usuario != PegaUsuarioLogado())
            {
                existe = false;
                return existe;
            }
            return existe;
        }

        private Prova ValoresProva(int? id)
        {
            // Instancia e atribui valores aos objetos da prova.
            Cabecalho cabecalho = db.Cabecalho.Find(id);
            Colegio colegio = db.Colegio.Find(cabecalho.Cod_colegio);
            Materia materia = db.Questao.Where(q => q.Cod_prova == cabecalho.Cod_prova).Select(m => m.Materia).FirstOrDefault();
            Assunto assunto = db.Questao.Where(q => q.Cod_prova == cabecalho.Cod_prova).Select(a => a.Assunto).FirstOrDefault();
            Turma turma = db.Turma.Find(cabecalho.Cod_turma);

            Prova prova = new Prova
            {
                Cabecalho = cabecalho,
                Colegio = colegio,
                Materia = materia,
                Assunto = assunto,
                Turma = turma
            };

            // Se a imagem de cabecalho existir, mostra ela.
            if (cabecalho.Imagem_cabecalho != null)
            {
                var base64 = Convert.ToBase64String(cabecalho.Imagem_cabecalho);
                var imagemCabecalho = string.Format("data:image/png;base64,{0}", base64);
                ViewBag.ImagemCabecalho = imagemCabecalho;
            }

            // Busca a lista de questões da prova inserida.
            prova.ListaQuestoes = db.Questao.Where(q => q.Cod_prova == prova.Cabecalho.Cod_prova).Include(o => o.Opcao).ToList();

            return prova;
        }
        #endregion

        #region Index
        // GET: Prova
        public ActionResult Index()
        {
            return View();
        }
        #endregion

        #region Nova
        // GET: Prova/Nova
        public ActionResult Nova()
        {
            return View();
        }

        // POST: Prova/Nova
        // Salvar questão
        [ValidateAntiForgeryToken]
        [HttpPost]
        public ActionResult Nova(Prova prova)
        {
            if (ModelState.IsValid)
            {
                if (prova.Questao.Valor_questao > prova.Cabecalho.Valor_prova)
                {
                    ModelState.AddModelError("", "O valor da questão não pode ser maior que o valor da prova.");
                    return View(prova);
                }

                // Pega o ID do usuário logado e o define no cabeçalho.
                var identity = (ClaimsIdentity)User.Identity;

ProvaFacil/ProvaFacil/Views/Prova/Detalhes.cshtml
@{
    ViewBag.Title = "Detalhes";
}

<div class="row" style="margin: auto">
    <a href="@Url.Action("Lista", "Prova")">
        <div class="visualizarProvas" style="height: 50px; color: #53bbd3; border-color: #53bbd3">
            <i class="fas fa-chevron-circle-left fa-lg"></i>
            Voltar para a lista
        </div>
    </a>

    <a href="@Url.Action("GerarPDF", "Prova", new { id = Model.Id })" style="margin-left: 750px">
        <div class="visualizarProvas" style="width: 150px; height: 50px; color: #eb4d4b; border-color: #eb4d4b">
            <i class="far fa-file-pdf fa-lg"></i>
            Gerar PDF
        </div>
    </a>
</div>

<div style="border: 1px solid black; padding: 30px; margin-top: 3%">
    @Html.Action("VisualizarPDF")
</div>

ProvaFacil/ProvaFacil/Views/Prova/Excluir.cshtml
@model ProvaFacil.Models.Prova

@{
    ViewBag.Title = "Excluir";
}

<div class="row" style="margin: auto">
    <a href="@Url.Action("Lista", "Prova")">
        <div class="visualizarProvas" style="height: 50px; color: #53bbd3; border-color: #53bbd3">
            <i class="fas fa-chevron-circle-left fa-lg"></i>
            Voltar para a lista
        </div>
    </a>
</div>
<br />
<h2>Tem certeza que deseja excluir esta prova?</h2>
<div>
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Colegio.Nome_colegio)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Colegio.Nome_colegio)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Cabecalho.Data_prova)
        </dt>

        <dd>
            @Convert.ToString(string.Format("{0:dd/MM/yyyy}", Model.Cabecalho.Data_prova))
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Cabecalho.Valor_prova)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Cabecalho.Valor_prova)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Materia.Nome_materia)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Materia.Nome_materia)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Assunto.Nome_assunto)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Assunto.Nome_assunto)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Turma.Turno)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Turma.Turno)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Turma.Nivel)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Turma.Nivel)
        </dd>
    </dl>
    <br />
    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <input type="submit" value="Excluir" class="btn btn-danger" />
    }
</div>

ProvaFacil/ProvaFacil/Views/Prova/Index.cshtml
@{
    ViewBag.Title = "Provas";
}

<div class="row" style="margin: auto">
    <a href="@Url.Action("Index", "Home")">
        <div class="titulo">
            Prova<br />
            Fácil
        </div>
    </a>

    <div style="margin: auto">
        <h1 class="display-4" style="text-align: center; font-size: 40px">Bem vindo, <b>@User.Identity.Name</b></h1>
    </div>
</div>

<div class="row" style="margin: auto">
    <a style="margin-top: 3%" href="@Url.Action("Nova", "Prova")">
        <div class="novaProva">
            <img src="~/Content/Prova/icone_adicionarprova.png" style="width: 20%" />
            Nova prova
        </div>
    </a>
    <a style="margin-top: 3%; margin-left: 3%" href="@Url.Action("Lista", "Prova")">
        <div class="visualizarProvas">
            <img src="~/Content/Prova/icone_visualizarprovas.png" style="width: 20%" />
            Visualizar provas
        </div>
    </a>
</div>

ProvaFacil/ProvaFacil/Views/Prova/Lista.cshtml
@model IEnumerable<ProvaFacil.Models.Cabecalho>

@{
    ViewBag.Title = "Lista";
}

<div class="row" style="margin: auto">
    <a href="@Url.Action("Index", "Home")">
        <div class="titulo">
            Prova<br />
            Fácil
        </div>
    </a>

    <div style="margin: auto">
        <h1 style="text-align: center; color: #53bbd3">Lista de provas</h1>
    </div>
</div>

<table class="table table-bordered" style="margin-top: 3%">
    <thead class="thead-light" style="text-align:center">
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Colegio.Nome_colegio)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Data_prova)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Valor_prova)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Questao.FirstOrDefault().Materia.Nome_materia)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Questao.FirstOrDefault().Assunto.Nome_assunto)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Turma.Turno)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Turma.Nivel)
            </th>
            <th>
                Ações
            </th>
        </tr>

        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Colegio.Nome_colegio)
                </td>
                <td>
                    @Convert.ToString(string.Format("{0:dd/MM/yyyy}", item.Data_prova))
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Valor_prova)
                </td>
                <td>
                    @Html.DisplayFor(model => item.Questao.FirstOrDefault().Materia.Nome_materia)
                </td>
                <td>
                    @Html.DisplayFor(model => item.Questao.FirstOrDefault().Assunto.Nome_assunto)
                </td>
                <td>
                    @Html.DisplayFor(model => item.Turma.Turno)
                </td>
                <td>
                    @Html.DisplayFor(model => item.Turma.Nivel)
                </td>
                <td>
                    @*@Html.ActionLink(" ", "Edit", new { id = item.Cod_prova }, new { @class = "fas fa-edit fa-lg", @style = "color: orange" })*@
                    @Html.ActionLink(" ", "Detalhes", new { id = item.Cod_prova }, new { @class = "fas fa-info-circle fa-lg", @style = "color: #5DBCD2" })
                    @*@Html.ActionLink(" ", "Excluir", new { id = item.Cod_prova }, new { @class = "fas fa-trash-alt fa-lg", @style = "color: red" })*@
                </td>
            </tr>
        }
</table>

ProvaFacil/ProvaFacil/Views/Prova/_VisualizarPDF.cshtml
@model ProvaFacil.Models.Prova

<!DOCTYPE html>
<html>
<head>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.0/css/all.css" />
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Prova Fácil</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="container body-content">
        @Scripts.Render("~/bundles/jquery")
        @Scripts.Render("~/bundles/bootstrap")
        @if (ViewBag.ImagemCabecalho != null)
        {
            <img src="@ViewBag.ImagemCabecalho" style="margin-bottom: 2%; width: 1010px; height: 150px" />
        }

        <div class="h5">
            <ul class="list-inline" style="text-align: center">
                <li class="list-inline-item">@Html.DisplayFor(model => model.Cabecalho.Colegio.Nome_colegio)</li>
            </ul>
            <ul class="list-inline">
                <li class="list-inline-item">Nome: _________________________________________________________</li>
                <li class="list-inline-item" style="margin-left: 1%; margin-right: 3%">
                    @if (Model.Cabecalho.Data_prova != null)
                    {
                        <h5>Data: @Convert.ToString(string.Format("{0:dd/MM/yyyy}", Model.Cabecalho.Data_prova))</h5>
                    }
                    else
                    {
                        <h5>Data: ___/___/_____</h5>
                    }
                </li>
                <li class="list-inline-item">Valor: @Html.DisplayFor(model => model.Cabecalho.Valor_prova)</li>
                <li class="list-inline-item" style="margin-left: 3%">Nota: ______</li>
            </ul>
            <ul class="list-inline">
                <li class="list-inline-item">Matéria: @Html.DisplayFor(model => model.Materia.Nome_materia)</li>
                <li class="list-inline-item" style="margin-left: 10%">Assunto: @Html.DisplayFor(model => model.Assunto.Nome_assunto)</li>
                <li class="list-inline-item" style="margin-left: 9%">@Html.DisplayFor(model => model.Turma.Turno)</li>
                <li class="list-inline-item" style="margin-left: 9%">@Html.DisplayFor(model => model.Turma.Nivel)</li>
            </ul>
        </div>

        <div class="h5" style="margin-top: 3%">
            @for (int i = 1; i <= Model.ListaQuestoes.Count; i++)
            {
                <br /> <h5>
                    @i) @Model.ListaQuestoes[i - 1].Descricao_questao @if (Model.ListaQuestoes[i - 1].Valor_questao != null)
                    {
                        @: (@Model.ListaQuestoes[i - 1].Valor_questao)
                    }
                </h5>
                if (Model.ListaQuestoes[i - 1].Tipo_questao == "Dissertativa")
                {
                    for (int j = 0; j < Model.ListaQuestoes[i - 1].Numero_linhas; j++)
                    {
                        <hr style="border: 1px solid black; margin-top: 3%" />
                    }
                }
                else if (Model.ListaQuestoes[i - 1].Tipo_questao == "Múltipla escolha" || Model.ListaQuestoes[i - 1].Tipo_questao == "Verdadeiro/falso")
                {
                    foreach (var opcao in Model.ListaQuestoes[i - 1].Opcao)
                    {
                        if (opcao.Descricao_opcao != null)
                        {
                            <h5>(&emsp;)&ensp;@opcao.Descricao_opcao</h5>
                        }
                    }
                }
            }
        </div>
    </div>
</body>
</html>